// api/proto/orchestrator.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/orchestrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Deployment messages
type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Replicas      int32                  `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Cpu           float64                `protobuf:"fixed64,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int64                  `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HealthCheck   *HealthCheck           `protobuf:"bytes,8,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	Strategy      *DeploymentStrategy    `protobuf:"bytes,9,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *DeployRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DeployRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *DeployRequest) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *DeployRequest) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *DeployRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *DeployRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DeployRequest) GetHealthCheck() *HealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *DeployRequest) GetStrategy() *DeploymentStrategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ContainerIds  []string               `protobuf:"bytes,3,rep,name=container_ids,json=containerIds,proto3" json:"container_ids,omitempty"`
	SuccessRate   float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *DeployResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeployResponse) GetContainerIds() []string {
	if x != nil {
		return x.ContainerIds
	}
	return nil
}

func (x *DeployResponse) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *DeployResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Delete messages
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeleteRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type DeleteResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message             string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DeletedContainerIds []string               `protobuf:"bytes,3,rep,name=deleted_container_ids,json=deletedContainerIds,proto3" json:"deleted_container_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteResponse) GetDeletedContainerIds() []string {
	if x != nil {
		return x.DeletedContainerIds
	}
	return nil
}

// Status messages
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *StatusRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*DeploymentStatus    `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	Containers    []*ContainerStatus     `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetDeployments() []*DeploymentStatus {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *StatusResponse) GetContainers() []*ContainerStatus {
	if x != nil {
		return x.Containers
	}
	return nil
}

type DeploymentStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId      string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	RunningContainers int32                  `protobuf:"varint,4,opt,name=running_containers,json=runningContainers,proto3" json:"running_containers,omitempty"`
	DesiredContainers int32                  `protobuf:"varint,5,opt,name=desired_containers,json=desiredContainers,proto3" json:"desired_containers,omitempty"`
	SuccessRate       float64                `protobuf:"fixed64,6,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeploymentStatus) Reset() {
	*x = DeploymentStatus{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentStatus) ProtoMessage() {}

func (x *DeploymentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentStatus.ProtoReflect.Descriptor instead.
func (*DeploymentStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *DeploymentStatus) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeploymentStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeploymentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeploymentStatus) GetRunningContainers() int32 {
	if x != nil {
		return x.RunningContainers
	}
	return 0
}

func (x *DeploymentStatus) GetDesiredContainers() int32 {
	if x != nil {
		return x.DesiredContainers
	}
	return 0
}

func (x *DeploymentStatus) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *DeploymentStatus) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ContainerStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContainerId     string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	DeploymentId    string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	State           string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	NodeId          string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Region          string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Healthy         bool                   `protobuf:"varint,7,opt,name=healthy,proto3" json:"healthy,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastHealthCheck int64                  `protobuf:"varint,9,opt,name=last_health_check,json=lastHealthCheck,proto3" json:"last_health_check,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContainerStatus) Reset() {
	*x = ContainerStatus{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatus) ProtoMessage() {}

func (x *ContainerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatus.ProtoReflect.Descriptor instead.
func (*ContainerStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerStatus) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerStatus) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *ContainerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ContainerStatus) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ContainerStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ContainerStatus) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ContainerStatus) GetLastHealthCheck() int64 {
	if x != nil {
		return x.LastHealthCheck
	}
	return 0
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	EventTypes    []string               `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *StreamRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *StreamRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *Event) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     string                 `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"` // "1h", "24h", "7d"
	Regions       []string               `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *MetricsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *MetricsRequest) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

type MetricsResponse struct {
	state                 protoimpl.MessageState    `protogen:"open.v1"`
	DeploymentSuccessRate float64                   `protobuf:"fixed64,1,opt,name=deployment_success_rate,json=deploymentSuccessRate,proto3" json:"deployment_success_rate,omitempty"`
	TotalContainers       int32                     `protobuf:"varint,2,opt,name=total_containers,json=totalContainers,proto3" json:"total_containers,omitempty"`
	HealthyContainers     int32                     `protobuf:"varint,3,opt,name=healthy_containers,json=healthyContainers,proto3" json:"healthy_containers,omitempty"`
	RegionMetrics         map[string]*RegionMetrics `protobuf:"bytes,4,rep,name=region_metrics,json=regionMetrics,proto3" json:"region_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SchedulingMetrics     *SchedulingMetrics        `protobuf:"bytes,5,opt,name=scheduling_metrics,json=schedulingMetrics,proto3" json:"scheduling_metrics,omitempty"`
	RecentDeployments     []*RecentDeployment       `protobuf:"bytes,6,rep,name=recent_deployments,json=recentDeployments,proto3" json:"recent_deployments,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *MetricsResponse) GetDeploymentSuccessRate() float64 {
	if x != nil {
		return x.DeploymentSuccessRate
	}
	return 0
}

func (x *MetricsResponse) GetTotalContainers() int32 {
	if x != nil {
		return x.TotalContainers
	}
	return 0
}

func (x *MetricsResponse) GetHealthyContainers() int32 {
	if x != nil {
		return x.HealthyContainers
	}
	return 0
}

func (x *MetricsResponse) GetRegionMetrics() map[string]*RegionMetrics {
	if x != nil {
		return x.RegionMetrics
	}
	return nil
}

func (x *MetricsResponse) GetSchedulingMetrics() *SchedulingMetrics {
	if x != nil {
		return x.SchedulingMetrics
	}
	return nil
}

func (x *MetricsResponse) GetRecentDeployments() []*RecentDeployment {
	if x != nil {
		return x.RecentDeployments
	}
	return nil
}

// Supporting message types
type HealthCheck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "http", "tcp", "exec"
	Endpoint        string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Domain          string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,4,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	TimeoutSeconds  int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Retries         int32                  `protobuf:"varint,6,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *HealthCheck) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HealthCheck) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *HealthCheck) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *HealthCheck) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *HealthCheck) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HealthCheck) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

type DeploymentStrategy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "rolling", "blue-green", "canary"
	MaxUnavailable   int32                  `protobuf:"varint,2,opt,name=max_unavailable,json=maxUnavailable,proto3" json:"max_unavailable,omitempty"`
	MaxSurge         int32                  `protobuf:"varint,3,opt,name=max_surge,json=maxSurge,proto3" json:"max_surge,omitempty"`
	CanaryPercentage int32                  `protobuf:"varint,4,opt,name=canary_percentage,json=canaryPercentage,proto3" json:"canary_percentage,omitempty"` // For canary deployments
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeploymentStrategy) Reset() {
	*x = DeploymentStrategy{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentStrategy) ProtoMessage() {}

func (x *DeploymentStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentStrategy.ProtoReflect.Descriptor instead.
func (*DeploymentStrategy) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *DeploymentStrategy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DeploymentStrategy) GetMaxUnavailable() int32 {
	if x != nil {
		return x.MaxUnavailable
	}
	return 0
}

func (x *DeploymentStrategy) GetMaxSurge() int32 {
	if x != nil {
		return x.MaxSurge
	}
	return 0
}

func (x *DeploymentStrategy) GetCanaryPercentage() int32 {
	if x != nil {
		return x.CanaryPercentage
	}
	return 0
}

type RegionMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ContainerCount    int32                  `protobuf:"varint,1,opt,name=container_count,json=containerCount,proto3" json:"container_count,omitempty"`
	CpuUtilization    float64                `protobuf:"fixed64,2,opt,name=cpu_utilization,json=cpuUtilization,proto3" json:"cpu_utilization,omitempty"`
	MemoryUtilization float64                `protobuf:"fixed64,3,opt,name=memory_utilization,json=memoryUtilization,proto3" json:"memory_utilization,omitempty"`
	Availability      float64                `protobuf:"fixed64,4,opt,name=availability,proto3" json:"availability,omitempty"`
	NodeCount         int32                  `protobuf:"varint,5,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegionMetrics) Reset() {
	*x = RegionMetrics{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionMetrics) ProtoMessage() {}

func (x *RegionMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionMetrics.ProtoReflect.Descriptor instead.
func (*RegionMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *RegionMetrics) GetContainerCount() int32 {
	if x != nil {
		return x.ContainerCount
	}
	return 0
}

func (x *RegionMetrics) GetCpuUtilization() float64 {
	if x != nil {
		return x.CpuUtilization
	}
	return 0
}

func (x *RegionMetrics) GetMemoryUtilization() float64 {
	if x != nil {
		return x.MemoryUtilization
	}
	return 0
}

func (x *RegionMetrics) GetAvailability() float64 {
	if x != nil {
		return x.Availability
	}
	return 0
}

func (x *RegionMetrics) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

type SchedulingMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AvgLatencyMs    float64                `protobuf:"fixed64,1,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	P99LatencyMs    float64                `protobuf:"fixed64,2,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	TotalDecisions  int64                  `protobuf:"varint,3,opt,name=total_decisions,json=totalDecisions,proto3" json:"total_decisions,omitempty"`
	FailedDecisions int64                  `protobuf:"varint,4,opt,name=failed_decisions,json=failedDecisions,proto3" json:"failed_decisions,omitempty"`
	FailureReasons  map[string]int64       `protobuf:"bytes,5,rep,name=failure_reasons,json=failureReasons,proto3" json:"failure_reasons,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SchedulingMetrics) Reset() {
	*x = SchedulingMetrics{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulingMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulingMetrics) ProtoMessage() {}

func (x *SchedulingMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulingMetrics.ProtoReflect.Descriptor instead.
func (*SchedulingMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *SchedulingMetrics) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *SchedulingMetrics) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *SchedulingMetrics) GetTotalDecisions() int64 {
	if x != nil {
		return x.TotalDecisions
	}
	return 0
}

func (x *SchedulingMetrics) GetFailedDecisions() int64 {
	if x != nil {
		return x.FailedDecisions
	}
	return 0
}

func (x *SchedulingMetrics) GetFailureReasons() map[string]int64 {
	if x != nil {
		return x.FailureReasons
	}
	return nil
}

type RecentDeployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	SuccessRate   float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentDeployment) Reset() {
	*x = RecentDeployment{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentDeployment) ProtoMessage() {}

func (x *RecentDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentDeployment.ProtoReflect.Descriptor instead.
func (*RecentDeployment) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *RecentDeployment) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *RecentDeployment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecentDeployment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecentDeployment) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *RecentDeployment) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_orchestrator_proto protoreflect.FileDescriptor

const file_api_proto_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/orchestrator.proto\x12\forchestrator\"\x8f\x03\n" +
	"\rDeployRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1a\n" +
	"\breplicas\x18\x03 \x01(\x05R\breplicas\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\x01R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\x03R\x06memory\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12?\n" +
	"\x06labels\x18\a \x03(\v2'.orchestrator.DeployRequest.LabelsEntryR\x06labels\x12<\n" +
	"\fhealth_check\x18\b \x01(\v2\x19.orchestrator.HealthCheckR\vhealthCheck\x12<\n" +
	"\bstrategy\x18\t \x01(\v2 .orchestrator.DeploymentStrategyR\bstrategy\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\x0eDeployResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rcontainer_ids\x18\x03 \x03(\tR\fcontainerIds\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"W\n" +
	"\rDeleteRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"x\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x15deleted_container_ids\x18\x03 \x03(\tR\x13deletedContainerIds\"W\n" +
	"\rStatusRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"\x91\x01\n" +
	"\x0eStatusResponse\x12@\n" +
	"\vdeployments\x18\x01 \x03(\v2\x1e.orchestrator.DeploymentStatusR\vdeployments\x12=\n" +
	"\n" +
	"containers\x18\x02 \x03(\v2\x1d.orchestrator.ContainerStatusR\n" +
	"containers\"\x83\x02\n" +
	"\x10DeploymentStatus\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12-\n" +
	"\x12running_containers\x18\x04 \x01(\x05R\x11runningContainers\x12-\n" +
	"\x12desired_containers\x18\x05 \x01(\x05R\x11desiredContainers\x12!\n" +
	"\fsuccess_rate\x18\x06 \x01(\x01R\vsuccessRate\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\x99\x02\n" +
	"\x0fContainerStatus\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x18\n" +
	"\ahealthy\x18\a \x01(\bR\ahealthy\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12*\n" +
	"\x11last_health_check\x18\t \x01(\x03R\x0flastHealthCheck\"U\n" +
	"\rStreamRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\"\x97\x02\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12=\n" +
	"\bmetadata\x18\x06 \x03(\v2!.orchestrator.Event.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x0eMetricsRequest\x12\x1d\n" +
	"\n" +
	"time_range\x18\x01 \x01(\tR\ttimeRange\x12\x18\n" +
	"\aregions\x18\x02 \x03(\tR\aregions\"\xfa\x03\n" +
	"\x0fMetricsResponse\x126\n" +
	"\x17deployment_success_rate\x18\x01 \x01(\x01R\x15deploymentSuccessRate\x12)\n" +
	"\x10total_containers\x18\x02 \x01(\x05R\x0ftotalContainers\x12-\n" +
	"\x12healthy_containers\x18\x03 \x01(\x05R\x11healthyContainers\x12W\n" +
	"\x0eregion_metrics\x18\x04 \x03(\v20.orchestrator.MetricsResponse.RegionMetricsEntryR\rregionMetrics\x12N\n" +
	"\x12scheduling_metrics\x18\x05 \x01(\v2\x1f.orchestrator.SchedulingMetricsR\x11schedulingMetrics\x12M\n" +
	"\x12recent_deployments\x18\x06 \x03(\v2\x1e.orchestrator.RecentDeploymentR\x11recentDeployments\x1a]\n" +
	"\x12RegionMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.orchestrator.RegionMetricsR\x05value:\x028\x01\"\xc3\x01\n" +
	"\vHealthCheck\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12)\n" +
	"\x10interval_seconds\x18\x04 \x01(\x05R\x0fintervalSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x18\n" +
	"\aretries\x18\x06 \x01(\x05R\aretries\"\x9b\x01\n" +
	"\x12DeploymentStrategy\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12'\n" +
	"\x0fmax_unavailable\x18\x02 \x01(\x05R\x0emaxUnavailable\x12\x1b\n" +
	"\tmax_surge\x18\x03 \x01(\x05R\bmaxSurge\x12+\n" +
	"\x11canary_percentage\x18\x04 \x01(\x05R\x10canaryPercentage\"\xd3\x01\n" +
	"\rRegionMetrics\x12'\n" +
	"\x0fcontainer_count\x18\x01 \x01(\x05R\x0econtainerCount\x12'\n" +
	"\x0fcpu_utilization\x18\x02 \x01(\x01R\x0ecpuUtilization\x12-\n" +
	"\x12memory_utilization\x18\x03 \x01(\x01R\x11memoryUtilization\x12\"\n" +
	"\favailability\x18\x04 \x01(\x01R\favailability\x12\x1d\n" +
	"\n" +
	"node_count\x18\x05 \x01(\x05R\tnodeCount\"\xd4\x02\n" +
	"\x11SchedulingMetrics\x12$\n" +
	"\x0eavg_latency_ms\x18\x01 \x01(\x01R\favgLatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\x02 \x01(\x01R\fp99LatencyMs\x12'\n" +
	"\x0ftotal_decisions\x18\x03 \x01(\x03R\x0etotalDecisions\x12)\n" +
	"\x10failed_decisions\x18\x04 \x01(\x03R\x0ffailedDecisions\x12\\\n" +
	"\x0ffailure_reasons\x18\x05 \x03(\v23.orchestrator.SchedulingMetrics.FailureReasonsEntryR\x0efailureReasons\x1aA\n" +
	"\x13FailureReasonsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xa4\x01\n" +
	"\x10RecentDeployment\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp2\xef\x02\n" +
	"\fOrchestrator\x12C\n" +
	"\x06Deploy\x12\x1b.orchestrator.DeployRequest\x1a\x1c.orchestrator.DeployResponse\x12C\n" +
	"\x06Delete\x12\x1b.orchestrator.DeleteRequest\x1a\x1c.orchestrator.DeleteResponse\x12F\n" +
	"\tGetStatus\x12\x1b.orchestrator.StatusRequest\x1a\x1c.orchestrator.StatusResponse\x12B\n" +
	"\fStreamEvents\x12\x1b.orchestrator.StreamRequest\x1a\x13.orchestrator.Event0\x01\x12I\n" +
	"\n" +
	"GetMetrics\x12\x1c.orchestrator.MetricsRequest\x1a\x1d.orchestrator.MetricsResponseB5Z3github.com/iuliansafta/micro-orchestrator/api/protob\x06proto3"

var (
	file_api_proto_orchestrator_proto_rawDescOnce sync.Once
	file_api_proto_orchestrator_proto_rawDescData []byte
)

func file_api_proto_orchestrator_proto_rawDescGZIP() []byte {
	file_api_proto_orchestrator_proto_rawDescOnce.Do(func() {
		file_api_proto_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_orchestrator_proto_rawDesc), len(file_api_proto_orchestrator_proto_rawDesc)))
	})
	return file_api_proto_orchestrator_proto_rawDescData
}

var file_api_proto_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_orchestrator_proto_goTypes = []any{
	(*DeployRequest)(nil),      // 0: orchestrator.DeployRequest
	(*DeployResponse)(nil),     // 1: orchestrator.DeployResponse
	(*DeleteRequest)(nil),      // 2: orchestrator.DeleteRequest
	(*DeleteResponse)(nil),     // 3: orchestrator.DeleteResponse
	(*StatusRequest)(nil),      // 4: orchestrator.StatusRequest
	(*StatusResponse)(nil),     // 5: orchestrator.StatusResponse
	(*DeploymentStatus)(nil),   // 6: orchestrator.DeploymentStatus
	(*ContainerStatus)(nil),    // 7: orchestrator.ContainerStatus
	(*StreamRequest)(nil),      // 8: orchestrator.StreamRequest
	(*Event)(nil),              // 9: orchestrator.Event
	(*MetricsRequest)(nil),     // 10: orchestrator.MetricsRequest
	(*MetricsResponse)(nil),    // 11: orchestrator.MetricsResponse
	(*HealthCheck)(nil),        // 12: orchestrator.HealthCheck
	(*DeploymentStrategy)(nil), // 13: orchestrator.DeploymentStrategy
	(*RegionMetrics)(nil),      // 14: orchestrator.RegionMetrics
	(*SchedulingMetrics)(nil),  // 15: orchestrator.SchedulingMetrics
	(*RecentDeployment)(nil),   // 16: orchestrator.RecentDeployment
	nil,                        // 17: orchestrator.DeployRequest.LabelsEntry
	nil,                        // 18: orchestrator.Event.MetadataEntry
	nil,                        // 19: orchestrator.MetricsResponse.RegionMetricsEntry
	nil,                        // 20: orchestrator.SchedulingMetrics.FailureReasonsEntry
}
var file_api_proto_orchestrator_proto_depIdxs = []int32{
	17, // 0: orchestrator.DeployRequest.labels:type_name -> orchestrator.DeployRequest.LabelsEntry
	12, // 1: orchestrator.DeployRequest.health_check:type_name -> orchestrator.HealthCheck
	13, // 2: orchestrator.DeployRequest.strategy:type_name -> orchestrator.DeploymentStrategy
	6,  // 3: orchestrator.StatusResponse.deployments:type_name -> orchestrator.DeploymentStatus
	7,  // 4: orchestrator.StatusResponse.containers:type_name -> orchestrator.ContainerStatus
	18, // 5: orchestrator.Event.metadata:type_name -> orchestrator.Event.MetadataEntry
	19, // 6: orchestrator.MetricsResponse.region_metrics:type_name -> orchestrator.MetricsResponse.RegionMetricsEntry
	15, // 7: orchestrator.MetricsResponse.scheduling_metrics:type_name -> orchestrator.SchedulingMetrics
	16, // 8: orchestrator.MetricsResponse.recent_deployments:type_name -> orchestrator.RecentDeployment
	20, // 9: orchestrator.SchedulingMetrics.failure_reasons:type_name -> orchestrator.SchedulingMetrics.FailureReasonsEntry
	14, // 10: orchestrator.MetricsResponse.RegionMetricsEntry.value:type_name -> orchestrator.RegionMetrics
	0,  // 11: orchestrator.Orchestrator.Deploy:input_type -> orchestrator.DeployRequest
	2,  // 12: orchestrator.Orchestrator.Delete:input_type -> orchestrator.DeleteRequest
	4,  // 13: orchestrator.Orchestrator.GetStatus:input_type -> orchestrator.StatusRequest
	8,  // 14: orchestrator.Orchestrator.StreamEvents:input_type -> orchestrator.StreamRequest
	10, // 15: orchestrator.Orchestrator.GetMetrics:input_type -> orchestrator.MetricsRequest
	1,  // 16: orchestrator.Orchestrator.Deploy:output_type -> orchestrator.DeployResponse
	3,  // 17: orchestrator.Orchestrator.Delete:output_type -> orchestrator.DeleteResponse
	5,  // 18: orchestrator.Orchestrator.GetStatus:output_type -> orchestrator.StatusResponse
	9,  // 19: orchestrator.Orchestrator.StreamEvents:output_type -> orchestrator.Event
	11, // 20: orchestrator.Orchestrator.GetMetrics:output_type -> orchestrator.MetricsResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_orchestrator_proto_init() }
func file_api_proto_orchestrator_proto_init() {
	if File_api_proto_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_orchestrator_proto_rawDesc), len(file_api_proto_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_orchestrator_proto_goTypes,
		DependencyIndexes: file_api_proto_orchestrator_proto_depIdxs,
		MessageInfos:      file_api_proto_orchestrator_proto_msgTypes,
	}.Build()
	File_api_proto_orchestrator_proto = out.File
	file_api_proto_orchestrator_proto_goTypes = nil
	file_api_proto_orchestrator_proto_depIdxs = nil
}
